In [0]:
import os, pickle, re, sklearn, string
import numpy as np
import matplotlib.pyplot as plt

from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split




In [4]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')# Download text data sets, including stop words
from nltk.corpus import stopwords # Import the stop word list
import re
from bs4 import BeautifulSoup


# Download the punkt tokenizer for sentence splitting
import nltk.data
nltk.download('punkt')   

# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')


from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords


class Creat_vocabulary():
  
  def __init__(self):
    self.sentences = []
    self.word2idx = {}
    self.idx2word = {}
    self.idx_pairs = []
    self.all_voc = []
    self.negative_pairs = []
    
    
  def get_sentence(self):
    
      return self.sentences
    
    
  def get_word2idx(self):
    
      return self.word2idx
  
  
  def get_idx2word(self):
    
      return self.idx2word
  
  
  def get_idx_pairs(self):
    
      return self.idx_pairs
    
  def expand(self,ListofList):
    
    for ll in ListofList:
      for l in ll:
        self.all_voc.append(l)
    return self.all_voc   
  

  # Define a function to split a review into parsed sentences
  def review_to_sentences( self, review, tokenizer, remove_stopwords=False ):
      # Function to split a review into parsed sentences. Returns a 
      # list of sentences, where each sentence is a list of words
    
      # 1. Use the NLTK tokenizer to split the paragraph into sentences
      raw_sentences = tokenizer.tokenize(review.strip())
    
    
      # 2. Loop over each sentence
      sentences = []
      for raw_sentence in raw_sentences:
      
          # If a sentence is empty, skip it
          if len(raw_sentence) > 0:
          
              # Otherwise, call review_to_wordlist to get a list of words
              sentences.append( self.review_to_wordlist( raw_sentence,remove_stopwords ))
    
      # Return List os List of Tokens in a sentence
      return sentences

  
  def review_to_wordlist(self, review, remove_stopwords=False ):
  
    # Function to convert a document to a sequence of words,
    # optionally removing stop words. Returns a list of words.

    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()

    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)

    # 3. Convert words to lower case and split them
    words = review_text.lower().split()

    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]

    # 5. Return a list of words
    return(words)


  def reviews_to_Words(self,data, tokenizer):
  
    sentences = []  # Initialize an empty list of sentences

    print ("Parsing sentences from training set")
  
    for review in data["review"]:
      self.sentences += self.review_to_sentences(review, tokenizer)
  
    return self.sentences
  
 
  
  def dictionary(self, tokenizer ):
    
    vocabulary = []
    for sentence in self.sentences:
      for token in sentence:
          if token not in vocabulary:
              vocabulary.append(token)

    self.word2idx = {w: idx for (idx, w) in enumerate(vocabulary)}
    self.idx2word = {idx: w for (idx, w) in enumerate(vocabulary)}

    vocabulary_size = len(vocabulary)
    
    return vocabulary_size, self.word2idx, self.idx2word
  
  def skip_contex_tuple(self,context_size):
    
    
    # changing context_size to window size
    if(context_size % 2 != 0):
      window_size = int(context_size + 1)//2
    else:
      window_size = int(context_size)//2
  
    #find context words around each word in a sentence and then coolect it in a list using vocab index in our dic
    for sentence in self.sentences:
      
      
      indices = [self.word2idx[word] for word in sentence]
      
      # for each word, threated as center word
      for center_word_pos in range(len(indices)):
        tup =[]
        
        for w in range(-window_size, window_size):
          cntx_pos = center_word_pos + w 
          

          if cntx_pos <=0 or cntx_pos>=len(indices) or cntx_pos == center_word_pos:

            continue
            
          tup.append(self.word2idx[sentence[cntx_pos]])
            
        # for each window position
        #tup = [sentence[center_word_pos + w ] for w in range(-window_size, window_size) if center_word_pos + w > 0 and center_word_pos + w <= len(indices) and center_word_pos  != center_word_pos + w ]

        self.idx_pairs.append((indices[center_word_pos], tup,1))

    self.idx_pairs = np.array(self.idx_pairs) # it will be useful to have this as numpy array
    
    return self.idx_pairs
  
  
  def get_negatives(self,idx_pairs, sampling_weights, K):
    
    all_negatives = []
    
    generator = RandomGenerator(sampling_weights)
    
    for pair in idx_pairs:
        negatives = []
        contexts = pair[1]
        center = pair[0]
        while len(negatives) <=  K:
          
            neg = generator.draw()
            
            # Noise words cannot be context words
            if neg not in contexts:
              
                negatives.append(neg)
                
        self.negative_pairs.append((center, negatives,0))
     
    self.negative_pairs = np.array(self.negative_pairs)
        
    return self.negative_pairs

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:

import random

class RandomGenerator(object):
    """Draw a random int in [0, n] according to n sampling weights"""
    def __init__(self, sampling_weights):
        self.population = list(range(len(sampling_weights)))
        self.sampling_weights = sampling_weights
        self.candidates = []
        self.i = 0

    def draw(self):
        if self.i == len(self.candidates):
            self.candidates = random.choices(
                self.population, self.sampling_weights, k=10000)
            self.i = 0
        self.i += 1
        return self.candidates[self.i-1]

      
      
      

generator = RandomGenerator([2,3,4])
[generator.draw() for _ in range(10)]

[0, 1, 1, 0, 2, 1, 0, 2, 2, 1]

In [6]:
from google.colab import drive
import glob
import os
import pandas as pd

#in order to use the dataset from MyDrive, need to mount it in google colab
drive.mount('/content/gdrive/')
path = '/content/gdrive/My Drive/data/labeledTrainData.tsv'

data2 = pd.read_csv(path, header=0, delimiter="\t", quoting=3)
data = data2['review']
target = data2['sentiment']

data1 = data2.iloc[1:200]

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [0]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

# create training and testing vars
train, test, ytrain, ytest = train_test_split(data, target, test_size=0.2)
#print X_train.shape, y_train.shape
#print X_test.shape, y_test.shape

In [0]:
xtrain = train.values.reshape(-1,1)

In [9]:
sentences = []  # Initialize an empty list of sentences
vocab =  Creat_vocabulary()
sentences =vocab.reviews_to_Words(data1 , tokenizer)

vocabulary_size, word2idx, idx2word = vocab.dictionary( tokenizer )

Parsing sentences from training set


In [0]:
import collections

listofV= vocab.get_sentence()

counter = collections.Counter(vocab.expand(listofV))


counters = list(counter.values())


sampling_weights = [counters[i]**0.75 for i in range(len(counters))]

vocab_size = len(counter)

In [0]:
idx_pairs = vocab.skip_contex_tuple(3)

all_negatives = vocab.get_negatives(idx_pairs, sampling_weights, 2)

In [0]:
CONTEXT_SIZE = len(all_negatives) + len(idx_pairs)

In [13]:
all_negatives

array([[0, list([741, 964, 741]), 0],
       [1, list([1961, 65, 3897]), 0],
       [2, list([1005, 866, 1818]), 0],
       ...,
       [3080, list([1415, 141, 6919]), 0],
       [0, list([4259, 3386, 132]), 0],
       [4010, list([226, 679, 5328]), 0]], dtype=object)

In [0]:
import torch
from torch import nn
import torch.nn.functional as F
from torch import optim



class Skipgram(nn.Module):

    def __init__(self, vocab_size, embedding_dim, context_size):
      
        super(Skipgram, self).__init__()
        
        
        self.embed_v = nn.Embedding(vocab_size, embedding_dim)
        
        self.embed_u = nn.Embedding(vocab_size, embedding_dim)
        
        
        initrange = 0.5 / embedding_dim
        self.embed_u.weight.data.uniform_(-initrange, initrange)
        self.embed_v.weight.data.uniform_(-0, 0)

        
        #self.linear1 = nn.Linear(embedding_dim, 128)
        #self.linear2 = nn.Linear(128, context_size * vocab_size)
        #self.parameters['context_size'] = context_size

 

    def forward(self,center, contexts,negatives):
        '''
        v = self.embed_v(center)
        u = self.embed_u(contexts)
        pred = torch.mm(v, u.view(200,1))
        log_probs = pred
        '''
        emb_u =  self.embed_u(center)
        emb_v =  self.embed_v(contexts)
        
        score = torch.mul(emb_u, emb_v).squeeze()
        #print(score)
        score = torch.sum(score)
        score = F.logsigmoid(score)
        neg_emb_v = self.embed_v(negatives)
        #print(neg_emb_v.size())
        #print(negatives)
        #print("*")
        #print(emb_u.unsqueeze(2).size())
        neg_score = torch.bmm(neg_emb_v, emb_u.unsqueeze(2)).squeeze()

        #neg_score = torch.mm(neg_emb_v, emb_u.view(-1,1)).squeeze()
        neg_score = F.logsigmoid(-1 * neg_score)
        
        return -1 * (torch.sum(score)+torch.sum(neg_score))
       
        #return log_probs
    
    def get_embed_v(self):
      
        return self.embed_v
      
      
    def get_embed_u(self):
      
        return self.embed_u
    
      
    def get_similar_tokens(self,query_token, k, embed,word2idx,idx2word):
      
      
        w = embed.weight
        x = w[word2idx[query_token]].view(-1,1)
        W = torch.transpose(w,0,-1)

        
        cos = nn.CosineSimilarity(dim=0, eps=1e-6)
        output = cos(W, x)
        print(output.size())

        values, indices = torch.topk(output, k=k, dim=0)
        indices = indices.data.numpy()
        
        for i in indices:
          print(idx2word[i])
          
          
          

losses = []
EMBEDDING_DIM = 200
CONTEXT_SIZE = len(all_negatives) + len(idx_pairs)
#loss_function =nn.BCEWithLogitsLoss()
model = Skipgram(vocab_size, EMBEDDING_DIM, CONTEXT_SIZE)
optimizer = optim.SGD(model.parameters(), lr=0.008)

In [93]:
neg_v = torch.tensor([negatives], dtype=torch.long)
context

tensor([[130,   5,   8]])

In [94]:
a= idx_pairs[i][0] 
a

372

In [0]:
from torch.autograd import Variable

losses= []
epoch = 7

for e in range(epoch):
  
  running_loss = 0
  

  for i in range(0,len(idx_pairs)):
  
  
  
  

    context = [i for i in idx_pairs[i][1] ]
    negatives = [i for i in all_negatives[i][1] ]

    
    context =Variable(torch.tensor([context]))
    neg_v = Variable(torch.tensor([negatives], dtype=torch.long))
    center = Variable(torch.tensor([idx_pairs[i][0]]))
    #print(neg_v)
    #print("VV")
    optimizer.zero_grad()
    loss =model.forward(center, context, neg_v)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
    losses.append(loss.item())

else:
  
  print(f"Training loss: {running_loss}")


In [88]:
min(losses)

2.772561550140381

In [0]:


'''
context_size = 3
embedding_dim = 126

model = nn.Sequential(
    
    
                      nn.Embedding(vocabulary_size, embedding_dim),
                      nn.Linear(embedding_dim,256),
                      nn.Linear(256,context_size * vocabulary_size),
                      nn.LogSoftmax(dim=1))



objective = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.003)
'''

from torch.autograd import Variable

losses= []
epoch = 4
tar = [0,1]
target = torch.tensor(tar, dtype=torch.long)
#target = target.view(1,-1)
for e in range(epoch):
  
  running_loss = 0

  for i in range(0,len(idx_pairs)):
    
    output =[]
    label = []
    for context in idx_pairs[i][1]:
      
        context = torch.tensor([context])
        center = torch.tensor([idx_pairs[i][0]])
        label1 = torch.tensor([idx_pairs[i][2]])
        aa=  model.forward(center, context)
        #print(aa)
        output.append(aa)
        label.append(label1)
        
        
    for negative in all_negatives[i][1]:
                      
        context = torch.tensor([negative], dtype=torch.long)
        center = torch.tensor([all_negatives[i][0]], dtype=torch.long)
        #label0 = torch.tensor([all_negatives[i][2]])
        label0 = torch.tensor([0])
        output.append(model.forward(center, context))
        label.append(label0)

        

    optimizer.zero_grad()
    
    output = Variable(torch.tensor([output], dtype=torch.float32),requires_grad=True)
    labelz = torch.tensor([label], dtype=torch.float32)


    loss = loss_function(output,labelz)    
    loss.backward()
    optimizer.step()
        
    running_loss += loss.item()
    losses.append(loss.item())
        
      
  else:
        print(f"Training loss: {running_loss}")

Training loss: 255439.17614002866
Training loss: 255439.17614002866
Training loss: 255439.17614002866
Training loss: 255439.17614002866


In [90]:
word2idx = vocab.get_word2idx()
idx2word = vocab.get_idx2word()

embed = model.get_embed_u()
k= 4
query_token = 'man'

s = model.get_similar_tokens(query_token, k, embed,word2idx,idx2word)

torch.Size([7120])
man
crappy
bossy
fatigue


In [0]:
w = embed.weight

In [0]:
word2idx["hines"]

7

In [0]:
idx2word[30]

'doing'

In [0]:
ss = w[7]
ss.size()

torch.Size([200])

In [0]:
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s',    level=logging.INFO)

def myhashfxn(obj):
    return hash(obj) % (2 ** 32)

# Set values for various parameters
num_features = 400    # Word vector dimensionality                      
min_word_count = 60   # Minimum word count                        
num_workers = 4       # Number of threads to run in parallel
context = 10          # Context window size                                                                                    
downsampling = 1e-3   # Downsample setting for frequent words


#**********************************************************



# Initialize and train the model (this will take some time)
from gensim.models import word2vec
#model = word2vec.Word2Vec(hashfxn=myhashfxn)

print ("Training model...")
model = word2vec.Word2Vec(sentences, workers=num_workers,             size=num_features, min_count = min_word_count,             window = context, sample = downsampling,hashfxn=myhashfxn)

# If you don't plan to train the model any further, calling 
# init_sims will make the model much more memory-efficient.
model.init_sims(replace=True)

# It can be helpful to create a meaningful model name and 
# save the model for later use. You can load it later using Word2Vec.load()
model_name = "300features_40minwords_10context"
model.save(model_name)


2019-06-06 02:15:44,719 : INFO : 'pattern' package not found; tag filters are not available for English
2019-06-06 02:15:44,729 : INFO : collecting all words and their counts
2019-06-06 02:15:44,730 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2019-06-06 02:15:44,786 : INFO : PROGRESS: at sentence #10000, processed 225803 words, keeping 17776 word types
2019-06-06 02:15:44,845 : INFO : PROGRESS: at sentence #20000, processed 451892 words, keeping 24948 word types
2019-06-06 02:15:44,901 : INFO : PROGRESS: at sentence #30000, processed 671315 words, keeping 30034 word types


Training model...


2019-06-06 02:15:44,963 : INFO : PROGRESS: at sentence #40000, processed 897815 words, keeping 34348 word types
2019-06-06 02:15:45,019 : INFO : PROGRESS: at sentence #50000, processed 1116963 words, keeping 37761 word types
2019-06-06 02:15:45,073 : INFO : PROGRESS: at sentence #60000, processed 1338404 words, keeping 40723 word types
2019-06-06 02:15:45,127 : INFO : PROGRESS: at sentence #70000, processed 1561580 words, keeping 43333 word types
2019-06-06 02:15:45,181 : INFO : PROGRESS: at sentence #80000, processed 1780887 words, keeping 45714 word types
2019-06-06 02:15:45,235 : INFO : PROGRESS: at sentence #90000, processed 2004996 words, keeping 48135 word types
2019-06-06 02:15:45,289 : INFO : PROGRESS: at sentence #100000, processed 2226966 words, keeping 50207 word types
2019-06-06 02:15:45,342 : INFO : PROGRESS: at sentence #110000, processed 2446580 words, keeping 52081 word types
2019-06-06 02:15:45,397 : INFO : PROGRESS: at sentence #120000, processed 2668775 words, keepin

In [0]:
model.doesnt_match("man woman child kitchen".split())


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `doesnt_match` (Method will be removed in 4.0.0, use self.wv.doesnt_match() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/gensim/models/keyedvectors.py:895: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)
/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


'kitchen'

In [0]:

model.most_similar("man")



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  
/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('woman', 0.6654655933380127),
 ('doctor', 0.6339104175567627),
 ('boy', 0.6286064982414246),
 ('journalist', 0.594315767288208),
 ('businessman', 0.5905495285987854),
 ('lady', 0.5899538397789001),
 ('guy', 0.5748952627182007),
 ('soldier', 0.5712598562240601),
 ('scientist', 0.5709996223449707),
 ('priest', 0.5663358569145203)]

In [0]:
#Vector Averaging
import numpy as np # Make sure that numpy is imported
def makeFeatureVec(words, model, num_features):
# Function to average all of the word vectors in a given
# paragraph
#
# Pre-initialize an empty numpy array (for speed)
    featureVec = np.zeros((num_features,),dtype="float32")
#
    nwords = 0.
#
# Index2word is a list that contains the names of the words in
# the model's vocabulary. Convert it to a set, for speed
    index2word_set = set(model.wv.index2word)
#
# Loop over each word in the review and, if it is in the model's
# vocaublary, add its feature vector to the total
    for word in words:
        if word in index2word_set:
            nwords = nwords + 1.
            featureVec = np.add(featureVec,model[word])
#
# Divide the result by the number of words to get the average
    featureVec = np.divide(featureVec,nwords)
    return featureVec



In [0]:
def getAvgFeatureVecs(reviews, model, num_features):
# Given a set of reviews (each one a list of words), calculate
# the average feature vector for each one and return a 2D numpy array
#
# Initialize a counter
    counter = 0
#
# Preallocate a 2D numpy array, for speed
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")
# Loop through the reviews
    for review in reviews:
        if counter%1000 == 0:
            print ("Review %d of %d" % (counter, len(reviews)))
        reviewFeatureVecs[counter] = makeFeatureVec(review, model,num_features)
#
# Increment the counter
        counter = counter + 1
    return reviewFeatureVecs




In [0]:
clean_train_reviews = []
for review in train1:
    clean_train_reviews.append( review_to_wordlist( review,         remove_stopwords=True ))
    
trainDataVecs = getAvgFeatureVecs( clean_train_reviews, model, num_features )
print ("Creating average feature vecs for test reviews")
clean_test_reviews = []
for review in test1:
    clean_test_reviews.append( review_to_wordlist( review,         remove_stopwords=True ))


# In[52]:

NameError: ignored

In [0]:
def expand(lll):
  s = []
  for ll in lll:
    for l in ll:
      s.append(l)
  return s   

In [0]:
l = [[1],[2,3],[4],[5],[5,5],[5],[5]]

q = expand(l)


In [0]:
print(q)

[1, 2, 3, 4, 5, 5, 5, 5, 5]


In [0]:
l = [[1],[2,3],[4],[5],[5,5],[5],[5]]
q = expand(l)

collections.Counter(q)

Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 5})

In [0]:
x0 = torch.randn(3, 4)
x = nn.LogSoftmax(dim=1)(x0)
x0, x

(tensor([[-1.5353,  0.3086, -2.6271,  1.6892],
         [ 1.2561,  0.1278,  0.1149,  0.2243],
         [ 0.1907, -0.0590,  0.6862, -0.7516]]),
 tensor([[-3.4904, -1.6464, -4.5822, -0.2659],
         [-0.6928, -1.8211, -1.8340, -1.7246],
         [-1.3376, -1.5873, -0.8422, -2.2800]]))

In [0]:
x.size()

torch.Size([3, 4])

In [0]:
y = torch.tensor([1.2, 2.3,3.3,5], dtype=torch.float32)
y

tensor([1.2000, 2.3000, 3.3000, 5.0000])

ValueError: ignored

In [0]:
x.size()

torch.Size([3, 1])

In [0]:
y.size()

torch.Size([3])

In [0]:
x.size()

torch.Size([3, 2])

In [0]:
x[:,:,None].size()

torch.Size([3, 2, 1])

In [0]:
W = torch.randn(3, 4)
W

tensor([[ 0.0749,  1.1305, -1.6960,  0.6326],
        [-0.4664,  0.2873,  0.0303,  0.8147],
        [-0.6050,  1.6914, -0.3439, -0.4138]])

In [0]:
y = torch.tensor([1.2, 2.3,3.3,5], dtype=torch.float32)

y

tensor([1.2000, 2.3000, 3.3000, 5.0000])

In [0]:
W = torch.tensor([[ 0.0749,  1.1305, -1.6960,  0.0],
        [-0.4664,  0.2873,  0.0303,  0.0],
        [-0.6050,  1.6914, -0.3439, 0.0]], dtype=torch.float32)
W

tensor([[ 0.0749,  1.1305, -1.6960,  0.0000],
        [-0.4664,  0.2873,  0.0303,  0.0000],
        [-0.6050,  1.6914, -0.3439,  0.0000]])

In [0]:
torch.max(x0,0)

torch.return_types.max(values=tensor([1.6308, 2.2339, 1.5731, 0.5754]), indices=tensor([2, 2, 0, 0]))

In [0]:
cos = nn.CosineSimilarity(dim=0, eps=1e-6)
output = cos(W,y)
output

tensor([-0.2386,  0.5331, -0.5869,  0.0000])

In [0]:
output = cos(W,y )
output

tensor([-0.2386,  0.5331, -0.5869,  0.0000])

In [0]:
s = torch.transpose(W,0,-1)
s.size()


torch.Size([4, 3])

In [0]:
z = torch.transpose(y.view(-1,1),0,-1)
z.size()




torch.Size([1, 4])

In [0]:
o = cos(z,W )
o.size()

torch.Size([4])

In [0]:
values, indices = torch.topk(output, k=3, dim=0)

In [0]:
values

tensor([ 1.5133,  0.0000, -1.1611])

In [0]:
indices.data.numpy()

array([1, 3, 2])